INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ADANA                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ADIYAMAN                      ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('AFYONKARAHİSAR                ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('AĞRI                          ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('AKSARAY                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('AMASYA                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ANKARA                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ANTALYA                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ARDAHAN                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ARTVİN                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('AYDIN                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('BALIKESİR                     ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('BARTIN                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('BATMAN                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('BAYBURT                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('BİLECİK                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('BİNGÖL                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('BİTLİS                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('BOLU                          ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('BURDUR                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('BURSA                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ÇANAKKALE                     ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ÇANKIRI                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ÇORUM                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('DENİZLİ                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('DİYARBAKIR                    ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('DÜZCE                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('EDİRNE                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ELAZIĞ                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ERZİNCAN                      ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ERZURUM                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ESKİŞEHİR                     ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('GAZİANTEP                     ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('GİRESUN                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('GÜMÜŞHANE                     ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('HAKKARİ                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('HATAY                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('IĞDIR                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ISPARTA                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('İSTANBUL                      ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('İZMİR                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('KAHRAMANMARAŞ                 ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('KARABÜK                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('KARAMAN                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('KARS                          ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('KASTAMONU                     ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('KAYSERİ                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('KIRIKKALE                     ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('KIRKLARELİ                    ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('KIRŞEHİR                      ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('KİLİS                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('KOCAELİ                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('KONYA                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('KÜTAHYA                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('MALATYA                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('MANİSA                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('MARDİN                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('MERSİN                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('MUĞLA                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('MUŞ                           ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('NEVŞEHİR                      ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('NİĞDE                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ORDU                          ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('OSMANİYE                      ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('RİZE                          ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('SAKARYA                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('SAMSUN                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('SİİRT                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('SİNOP                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('SİVAS                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ŞANLIURFA                     ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ŞIRNAK                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('TEKİRDAĞ                      ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('TOKAT                         ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('TRABZON                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('TUNCELİ                       ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('UŞAK                          ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('VAN                           ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('YALOVA                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('YOZGAT                        ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('ZONGULDAK                     ', 'Turkey', null);
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('New York', 'USA', 'New York');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Los Angeles', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Chicago', 'USA', 'Illinois');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Houston', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Philadelphia', 'USA', 'Pennsylvania');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Phoenix', 'USA', 'Arizona');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('San Antonio', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('San Diego', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Dallas', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('San Jose', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Austin', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Jacksonville', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Indianapolis', 'USA', 'Indiana');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('San Francisco', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Columbus', 'USA', 'Ohio');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Fort Worth', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Charlotte', 'USA', 'North Carolina');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Detroit', 'USA', 'Michigan');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('El Paso', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Memphis', 'USA', 'Tennessee');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Boston', 'USA', 'Massachusetts');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Seattle', 'USA', 'Washington');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Denver', 'USA', 'Colorado');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Washington', 'USA', 'District of Columbia');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Nashville', 'USA', 'Tennessee');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Baltimore', 'USA', 'Maryland');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Louisville', 'USA', 'Kentucky');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Portland', 'USA', 'Oregon');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Oklahoma City', 'USA', 'Oklahoma');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Milwaukee', 'USA', 'Wisconsin');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Las Vegas', 'USA', 'Nevada');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Albuquerque', 'USA', 'New Mexico');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Tucson', 'USA', 'Arizona');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Fresno', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Sacramento', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Long Beach', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Kansas City', 'USA', 'Missouri');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Mesa', 'USA', 'Arizona');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Virginia Beach', 'USA', 'Virginia');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Atlanta', 'USA', 'Georgia');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Colorado Springs', 'USA', 'Colorado');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Raleigh', 'USA', 'North Carolina');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Omaha', 'USA', 'Nebraska');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Miami', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Oakland', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Tulsa', 'USA', 'Oklahoma');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Minneapolis', 'USA', 'Minnesota');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Cleveland', 'USA', 'Ohio');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Wichita', 'USA', 'Kansas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Arlington', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('New Orleans', 'USA', 'Louisiana');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Bakersfield', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Tampa', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Honolulu', 'USA', 'Hawai''i');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Anaheim', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Aurora', 'USA', 'Colorado');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Santa Ana', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('St. Louis', 'USA', 'Missouri');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Riverside', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Corpus Christi', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Pittsburgh', 'USA', 'Pennsylvania');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Lexington', 'USA', 'Kentucky');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Anchorage', 'USA', 'Alaska');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Stockton', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Cincinnati', 'USA', 'Ohio');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Saint Paul', 'USA', 'Minnesota');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Toledo', 'USA', 'Ohio');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Newark', 'USA', 'New Jersey');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Greensboro', 'USA', 'North Carolina');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Plano', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Henderson', 'USA', 'Nevada');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Lincoln', 'USA', 'Nebraska');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Buffalo', 'USA', 'New York');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Fort Wayne', 'USA', 'Indiana');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Jersey City', 'USA', 'New Jersey');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Chula Vista', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Orlando', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('St. Petersburg', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Norfolk', 'USA', 'Virginia');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Chandler', 'USA', 'Arizona');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Laredo', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Madison', 'USA', 'Wisconsin');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Durham', 'USA', 'North Carolina');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Lubbock', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Winston-Salem', 'USA', 'North Carolina');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Garland', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Glendale', 'USA', 'Arizona');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Hialeah', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Reno', 'USA', 'Nevada');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Baton Rouge', 'USA', 'Louisiana');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Irvine', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Chesapeake', 'USA', 'Virginia');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Irving', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Scottsdale', 'USA', 'Arizona');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('North Las Vegas', 'USA', 'Nevada');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Fremont', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Gilbert', 'USA', 'Arizona');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('San Bernardino', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Boise', 'USA', 'Idaho');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Birmingham', 'USA', 'Alabama');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Rochester', 'USA', 'New York');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Richmond', 'USA', 'Virginia');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Spokane', 'USA', 'Washington');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Des Moines', 'USA', 'Iowa');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Montgomery', 'USA', 'Alabama');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Modesto', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Fayetteville', 'USA', 'North Carolina');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Tacoma', 'USA', 'Washington');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Shreveport', 'USA', 'Louisiana');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Fontana', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Oxnard', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Aurora', 'USA', 'Illinois');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Moreno Valley', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Akron', 'USA', 'Ohio');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Yonkers', 'USA', 'New York');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Columbus', 'USA', 'Georgia');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Augusta', 'USA', 'Georgia');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Little Rock', 'USA', 'Arkansas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Amarillo', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Mobile', 'USA', 'Alabama');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Huntington Beach', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Glendale', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Grand Rapids', 'USA', 'Michigan');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Salt Lake City', 'USA', 'Utah');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Tallahassee', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Huntsville', 'USA', 'Alabama');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Worcester', 'USA', 'Massachusetts');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Knoxville', 'USA', 'Tennessee');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Grand Prairie', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Newport News', 'USA', 'Virginia');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Brownsville', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Santa Clarita', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Overland Park', 'USA', 'Kansas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Providence', 'USA', 'Rhode Island');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Jackson', 'USA', 'Mississippi');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Garden Grove', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Oceanside', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Chattanooga', 'USA', 'Tennessee');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Fort Lauderdale', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Rancho Cucamonga', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Santa Rosa', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Port St. Lucie', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Ontario', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Tempe', 'USA', 'Arizona');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Vancouver', 'USA', 'Washington');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Springfield', 'USA', 'Missouri');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Cape Coral', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Pembroke Pines', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Sioux Falls', 'USA', 'South Dakota');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Peoria', 'USA', 'Arizona');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Lancaster', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Elk Grove', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Corona', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Eugene', 'USA', 'Oregon');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Salem', 'USA', 'Oregon');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Palmdale', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Salinas', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Springfield', 'USA', 'Massachusetts');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Pasadena', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Rockford', 'USA', 'Illinois');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Pomona', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Hayward', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Fort Collins', 'USA', 'Colorado');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Joliet', 'USA', 'Illinois');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Escondido', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Kansas City', 'USA', 'Kansas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Torrance', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Bridgeport', 'USA', 'Connecticut');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Alexandria', 'USA', 'Virginia');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Sunnyvale', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Cary', 'USA', 'North Carolina');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Lakewood', 'USA', 'Colorado');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Hollywood', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Paterson', 'USA', 'New Jersey');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Syracuse', 'USA', 'New York');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Naperville', 'USA', 'Illinois');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('McKinney', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Mesquite', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Clarksville', 'USA', 'Tennessee');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Savannah', 'USA', 'Georgia');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Dayton', 'USA', 'Ohio');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Orange', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Fullerton', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Pasadena', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Hampton', 'USA', 'Virginia');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('McAllen', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Killeen', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Warren', 'USA', 'Michigan');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('West Valley City', 'USA', 'Utah');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Columbia', 'USA', 'South Carolina');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('New Haven', 'USA', 'Connecticut');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Sterling Heights', 'USA', 'Michigan');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Olathe', 'USA', 'Kansas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Miramar', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Thousand Oaks', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Frisco', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Cedar Rapids', 'USA', 'Iowa');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Topeka', 'USA', 'Kansas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Visalia', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Waco', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Elizabeth', 'USA', 'New Jersey');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Bellevue', 'USA', 'Washington');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Gainesville', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Simi Valley', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Charleston', 'USA', 'South Carolina');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Carrollton', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Coral Springs', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Stamford', 'USA', 'Connecticut');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Hartford', 'USA', 'Connecticut');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Concord', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Roseville', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Thornton', 'USA', 'Colorado');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Kent', 'USA', 'Washington');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Lafayette', 'USA', 'Louisiana');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Surprise', 'USA', 'Arizona');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Denton', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Victorville', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Evansville', 'USA', 'Indiana');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Midland', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Santa Clara', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Athens', 'USA', 'Georgia');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Allentown', 'USA', 'Pennsylvania');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Abilene', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Beaumont', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Vallejo', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Independence', 'USA', 'Missouri');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Springfield', 'USA', 'Illinois');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Ann Arbor', 'USA', 'Michigan');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Provo', 'USA', 'Utah');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Peoria', 'USA', 'Illinois');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Norman', 'USA', 'Oklahoma');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Berkeley', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('El Monte', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Murfreesboro', 'USA', 'Tennessee');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Lansing', 'USA', 'Michigan');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Columbia', 'USA', 'Missouri');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Downey', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Costa Mesa', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Inglewood', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Miami Gardens', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Manchester', 'USA', 'New Hampshire');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Elgin', 'USA', 'Illinois');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Wilmington', 'USA', 'North Carolina');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Waterbury', 'USA', 'Connecticut');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Fargo', 'USA', 'North Dakota');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Arvada', 'USA', 'Colorado');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Carlsbad', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Westminster', 'USA', 'Colorado');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Rochester', 'USA', 'Minnesota');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Gresham', 'USA', 'Oregon');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Clearwater', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Lowell', 'USA', 'Massachusetts');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('West Jordan', 'USA', 'Utah');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Pueblo', 'USA', 'Colorado');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('San Buenaventura (Ventura)', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Fairfield', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('West Covina', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Billings', 'USA', 'Montana');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Murrieta', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('High Point', 'USA', 'North Carolina');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Round Rock', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Richmond', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Cambridge', 'USA', 'Massachusetts');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Norwalk', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Odessa', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Antioch', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Temecula', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Green Bay', 'USA', 'Wisconsin');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Everett', 'USA', 'Washington');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Wichita Falls', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Burbank', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Palm Bay', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Centennial', 'USA', 'Colorado');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Daly City', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Richardson', 'USA', 'Texas');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Pompano Beach', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Broken Arrow', 'USA', 'Oklahoma');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('North Charleston', 'USA', 'South Carolina');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('West Palm Beach', 'USA', 'Florida');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Boulder', 'USA', 'Colorado');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Rialto', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Santa Maria', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('El Cajon', 'USA', 'California');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Davenport', 'USA', 'Iowa');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Erie', 'USA', 'Pennsylvania');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Las Cruces', 'USA', 'New Mexico');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('South Bend', 'USA', 'Indiana');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Flint', 'USA', 'Michigan');
INSERT INTO CITY (CITY, COUNTRY, STATE) VALUES ('Kenosha', 'USA', 'Wisconsin');