apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibm-bai-flink-pvc
  namespace: ibmcp4a
spec:
  storageClassName: "ibmcp4a"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi