apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-my-kafka-bai-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /data/persistentvolumes/kafka/ibm-bai-pv
    server: 192.168.100.137
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: baiproject 
    name: datadir-my-kafka-bai-0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-my-kafka-bai-pv1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /data/persistentvolumes/bai/kafka/ibm-bai-pv1
    server: 192.168.100.137
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: baiproject
    name: datadir-my-kafka-bai-1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-my-kafka-bai-pv2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /data/persistentvolumes/bai/kafka/ibm-bai-pv2
    server: 192.168.100.137
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: baiproject
    name: datadir-my-kafka-bai-2
