apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-my-kafka-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /data/persistentvolumes/kafka/ibm-bai-pv
    server: 192.168.100.137
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: ibmcp4a 
    name: datadir-my-kafka-0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-my-kafka-pv1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /data/persistentvolumes/kafka/ibm-bai-pv1
    server: 192.168.100.137
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: ibmcp4a
    name: datadir-my-kafka-1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-my-kafka-pv2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /data/persistentvolumes/kafka/ibm-bai-pv2
    server: 192.168.100.137
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: ibmcp4a
    name: datadir-my-kafka-2
